# Generated by Django 5.2.5 on 2025-11-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('evaluacion', 'En Evaluación'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('reactivado', 'Reactivado')], default='activo', max_length=20),
        ),
    ]
